name: Build devcontainer
description: Build a devcontainer that is compliant with the spec

branding:
  icon: "activity"
  color: "green"

inputs:
  cache_src:
    description: Path for the docker cache source
    required: false
    default: /tmp/.buildx-cache
  cache_dest:
    description: Path for the docker cache destination
    required: false
    default: /tmp/.buildx-cache-new

runs:
  using: composite
  steps:
    - name: 🪂 Setup dotnet
      shell: bash
      run: |
        cat << EOL >> InfluxDB.yaml
        apiVersion: 1
        datasources:
          name: ${{ github.repository }}
          type: influxdb
          url: http://localhost:8086
          user: ${{ github.repository }}
          password:  ${{ github.repository }}
          database:  ${{ github.repository }}
          access: proxy
          editable: true
          isDefault: true
        EOL
        cat InfluxDB.yaml
